# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Testing Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
env:
  AWS_REGION: eu-central-1
  AWS_LIGHTSAIL_SERVICE_NAME: franklyapp
jobs:
  RunServer:
    concurrency: tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install AWS Client
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install || true
        aws --version
        curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "lightsailctl"
        sudo mv "lightsailctl" "/usr/local/bin/lightsailctl"
        sudo chmod +x /usr/local/bin/lightsailctl
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     - uses: actions/checkout@v3
     - name: Set up Python
       uses: actions/setup-python@v3
       with:
      python-version: '3.x'
     - name: Install dependencies
       run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest  
     - name: Running the server for tests
       run: |
          aws s3 cp s3://franklyappsecret/Env_Settings.cfg .
          python3 developmentserver.py
    
  Testing:
    concurrency: tests

    runs-on: ubuntu-latest

    steps:            
    - name: Test with pytest
      run: |    
            pytest
  Linter:
    concurrency: tests
    needs: Testing
    runs-on: ubuntu-latest
    steps:  
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
